# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1450, 879)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupShow = QtWidgets.QGroupBox(self.centralwidget)
        self.groupShow.setGeometry(QtCore.QRect(0, 90, 1451, 751))
        self.groupShow.setMinimumSize(QtCore.QSize(0, 0))
        self.groupShow.setStyleSheet("/*color: rgb(255, 255, 255);\n"
"background-color: rgb(31, 1, 94);*/\n"
"font: 75 10pt \"Aharoni\";")
        self.groupShow.setObjectName("groupShow")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupShow)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.img1 = QtWidgets.QLabel(self.groupShow)
        self.img1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.img1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.img1.setText("")
        self.img1.setObjectName("img1")
        self.horizontalLayout.addWidget(self.img1)
        self.img2 = QtWidgets.QLabel(self.groupShow)
        self.img2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.img2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.img2.setText("")
        self.img2.setObjectName("img2")
        self.horizontalLayout.addWidget(self.img2)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(1060, 10, 371, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lcdPeople = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdPeople.setObjectName("lcdPeople")
        self.horizontalLayout_2.addWidget(self.lcdPeople)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1450, 22))
        self.menubar.setObjectName("menubar")
        self.menuOnline = QtWidgets.QMenu(self.menubar)
        self.menuOnline.setObjectName("menuOnline")
        self.menuOffline = QtWidgets.QMenu(self.menubar)
        self.menuOffline.setObjectName("menuOffline")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_1 = QtWidgets.QAction(MainWindow)
        self.action_1.setObjectName("action_1")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.menuOnline.addAction(self.action_1)
        self.menuOnline.addAction(self.action_2)
        self.menuOffline.addAction(self.action_3)
        self.menuOffline.addAction(self.action_4)
        self.menubar.addAction(self.menuOnline.menuAction())
        self.menubar.addAction(self.menuOffline.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "基于YOLO的行人检测系统"))
        self.groupShow.setTitle(_translate("MainWindow", "显示区域"))
        self.label.setText(_translate("MainWindow", "实时人数"))
        self.menuOnline.setTitle(_translate("MainWindow", "离线识别"))
        self.menuOffline.setTitle(_translate("MainWindow", "在线识别"))
        self.action_1.setText(_translate("MainWindow", " 图片文件"))
        self.action_2.setText(_translate("MainWindow", "视频文件"))
        self.action_3.setText(_translate("MainWindow", "打开摄像头"))
        self.action_4.setText(_translate("MainWindow", "关闭摄像头"))
